version: '3.9'

services:
 # Website
  app:
    build:
      context: .
    container_name: WebsiteGudang
    ports:
      - "8081:80"
    networks:
      - web_net
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gudang
      - DB_USERNAME=root
      - DB_PASSWORD=root

 # Database
  mysql:
    image: mysql:latest
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web_net

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web_net

volumes:
  db_data:
    driver: local

networks:
  web_net:
    driver: bridge
